apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: alpine_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: WP_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: dbhost
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
