apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: alpine_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
        - name: WP_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: dbname
        - name: WP_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: dbuser
        - name: WP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: dbpassword
        - name: WP_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wp-secret
              key: dbhost
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
      - protocol: TCP
        port: 5050
        targetPort: 5050
